### ISSUE TITLE
Adding layers to LayerControl after initialization

### ISSUE THREAD

**Issue by m-mohr** [jbccollins/leaflet-tile-loading-progress-control#4]
Hey,

this is a very useful script, great work!

I am adding and removing layers after map initialization and it seems the library doesn't work if you add layers to the layerGroup in a later stage.

For example, you initialize the map with a basemap and the tile loading progress bar. It loads perfectly and shows the progress, but once I add a new layer to the map and the layerGroup, it doesn't show the loading progress.

Adding and removing the Control each time doesn't seem appropriate as it could destroy the loading progress, I think.

**Comment by m-mohr** [comment]
Hah, great. I just made the work around PR, but saw that you also made a fix already. Great work!

**Comment by jbccollins** [comment]
Version 1.0.4 has been published and should hopefully now support your use case 🤞. I have also updated the demo to reflect this. Lmk if you still have issues.

**Comment by m-mohr** [comment]
Thanks a lot for releasing 1.0.5.

Unfortunately, I get the following error:
```
TypeError: Cannot read property 'on' of undefined
    at NewClass.onAdd (Control.TileLoadingProgress.js:46)
    at NewClass.addTo (leaflet-src.js:4784)
    at VueComponent.createMap (MapViewer.vue:66)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at flushCallbacks (vue.runtime.esm.js:1906) "nextTick"
```

`leafletElt._map` is undefined, but this can be fixed by replacing it with `map`, which is passed to the function. Would you mind fixing this? :-) I tried the fix and it works for me.

**Comment by jbccollins** [comment]
What version of leaflet are you using? In 1.5.1 (and all 1.X versions that I've ever seen) most leaflet elements, including LayerGroup, have a `_map` property.
![Screen Shot 2019-07-24 at 1 49 06 PM](https://user-images.githubusercontent.com/8915552/61816329-2b478180-ae1a-11e9-9254-5e444aefb2d8.png)

**Comment by m-mohr** [comment]
I'm on 1.5.1. _map is not yet set for me in onAdd, not sure why exactly. I guess that's why they pass map to onAdd?!

**Comment by jbccollins** [comment]
Hmm ok. Welp I pushed 1.0.6 which should fix that. Apologies.

**Comment by jbccollins** [comment]
Aaaand I forgot to build 1.0.6 before publishing so scratch that. 1.0.7. 🤦

**Comment by m-mohr** [comment]
Thanks a lot, works! That has been probably the fastest bug fix I ever got in open source world.

Now, I'll check why the progress bar is appearing quite late after adding the layer and why the progress goes back and forth sometimes.

**Comment by jbccollins** [comment]
I'm not sure why the progress bar appears late but If you find something I'd be interested to hear it.
In my experience the progress bar goes back and forth a lot more when you zoom out rather than zoom in. Not sure why that is though.
